name: 'GolangCI Lint'

on:
  push:
    paths:
      - 'pkg/**'
      - 'main.go'
    branches:
      - master
  pull_request:
    paths:
      - 'pkg/**'
      - 'main.go'
    branches:
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v2
        with:
          golangci_lint_flags: "--tests=false"