name: "Testing"

on:
  push:
    paths:
      - "pkg/**"
      - "main.go"
    branches:
      - master
  pull_request:
    paths:
      - "pkg/**"
      - "main.go"
    branches:
      - master

jobs:
  unit-tests:
    strategy:
      matrix:
        go: ["1.21"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: |
          go install github.com/gotesttools/gotestfmt/v2/cmd/gotestfmt@latest
          cp config.example.yml config.yml
          task test
